general {
    lock_cmd = pidof hyprlock || hyprlock       # команда для блокировки
    before_sleep_cmd = loginctl lock-session    # блокировка ПЕРЕД засыпанием (в т.ч. при закрытии крышки)
    after_sleep_cmd = hyprctl dispatch dpms on  # включить экран после просыпания
}

# Блокировка экрана через 5 минут бездействия (опционально)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Сон через 10 минут бездействия (опционально)
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
